; SPDX-FileCopyrightText: Copyright contributors to the OSPO Code Scanner project
; SPDX-License-Identifier: Apache-2.0

MinAlertLevel = suggestion
Vocab = ProjectTerms

Packages = RedHat, alex

[[!.ospo-code-scanner][!LICENSE][!license]*.{md,txt,rst,ipynb,html}]
BasedOnStyles = RedHat, alex

[CODE_OF_CONDUCT.md]
BasedOnStyles =
