# SPDX-FileCopyrightText: Copyright contributors to the OSPO Code Scanner project
# SPDX-License-Identifier: Apache-2.0

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
